### ISSUE TITLE
Please remove Google analytics tracking

### ISSUE THREAD

**Issue by probonopd** [peteboothroyd/Dragoman#1]
Applications should not spy on users. This may even be illegal in some jurisdictions. cc @theassassin

https://github.com/peteboothroyd/Dragoman/blob/911c77074fe0438a387454d2712a89eccffeb073/app/index.tsx#L9-L11

**Comment by TheAssassin** [comment]
Yes, this kind of tracking is illegal in the EU, and probably many other jurisdictions as well.

**At least** opt out needs to be provided, also, you need to inform your users about the tracking. Furthermore, many privacy advocates and lawyers believe that even opt-in is required already. And as soon as the new EU Privacy and Electronic Communications Directive will be ratified by the European parliament at the latest, it will legal requirement to implement opt-in and a tracking free landing page where people can choose to either opt in or e.g. leave the page again.

Not to mention that software that tracks users like *this* is anything but trustworthy. Sure, you might wish to know where your app is used. But secret tracking, being illegal and morally questionable, is no solution. Even if it might be less informative, why not ask your user to fill in a form. If they give you the data on a voluntary base, you have their consent to process the data in the way you described it to them.

Please understand that collected data is nothing you can use as you will, and that collecting data is subject to many, many laws. Also, you should understand that collecting data is not the solution to anything, and collecting data, especially without the users' consent, because it "may be useful" one day is almost always illegal and against any free software principles.

**Comment by peteboothroyd** [comment]
Yes sorry about this I am working on getting an opt in message to users. I realise this probably should've been done first but I wasn't really expecting anybody apart from myself to be using it for a while! I'd be happy to take suggestions/contributions.

**Comment by TheAssassin** [comment]
I'd say you should get active yourself. Currently, your software performs illegal surveillance on users. You might even be sued for this, I don't think you want that.

**Comment by peteboothroyd** [comment]
No I don't want that. I'll take it down for now until this is fixed.

**Comment by peteboothroyd** [comment]
Ok this should be resolved now. Thanks for the feedback.

**Comment by TheAssassin** [comment]
I guess I should further tell you that you have to delete all the data collected illegally. To be on the safe side, I'd recommend to delete all the data you sent to Google.

By the way, I'd suggest to get rid of any Google services in this application. For analytics, check out [Piwik](https://piwik.org/), a FOSS software providing a mostly equivalent set of features. IIRC they have a hosted service, too.

**Comment by peteboothroyd** [comment]
Thanks again for bringing this to my attention. Just for the sake of completeness I wanted to mention that I have now removed the tracking code and deleted all the previous data.

**Comment by probonopd** [comment]
Thank you very much. Sorry if the request sounded a bit harsh, but it's better to not have legal risks in open source projects.
